### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by Jaimin19parmar** [openconnectivity/otgc-linux#25]
Hii everyone, 
When I am trying to onboard the new server then I got a null pointer exception.
`Exception in thread "Thread-28" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at org.openconnectivity.otgc.domain.model.resource.secure.doxm.OcDoxm.parseOCRepresentation(OcDoxm.java:130)
	at org.openconnectivity.otgc.data.repository.DoxsRepository.lambda$null$5(DoxsRepository.java:129)
`
Otgc-linux = **3.0.0**
System= **Ubuntu 20.04**

Let me know the possible cause and its solution.
Thanks :).

**Comment by dbartolomea** [comment]
Hello,
OTGC Linux v3.0.0 has been fully tested with Ubuntu 16.04 and 18.04. Please, try to make a clean installation on that system version and let us know if you still face that exception.
